var recipeList = [
{
name: "Beef Stroganoff",
cat: "Red Meat",
time: "1 Hour",
ingredients: "Kosher Salt<>Ground Black Pepper<>Chopped Fresh Parsley (for garnish)<>3/2 lbs Sirloin Roast or Beef Tenderloin<>2 Tablespoons All-Purpose Flour<>3/2 Teaspoons Hot Paprika<>1 Tablespoon Neutral Oil<>4 Tablespoons Unsalted Butter<>1/2 lb Button Mushrooms (cut into quarters)<>2 Small Shallots (thinly sliced)<>12 Oz Wide Egg Noodles<>1/4 Cup Dry White Wine<>1 Cup Heavy Cream<>3/2 Teaspoons Worcestershire Sauce<>3/2 Teaspoons Dijon Mustard",
steps: "Bring a large pot of salted water to a boil||Cut the beef against the grain into 1/2-inch slices, pound lightly, then cut those slices into 1-inch-wide strips||Add the flour, paprika, 3/2 teaspoons salt and 3/2 teaspoons pepper to a large shallow bowl, and toss to combine. Dredge the strips of meat in the flour mixture, shake them to remove excess flour, then transfer them to a rimmed baking sheet.||Place a large skillet over high heat, and swirl in the oil. When the oil begins to shimmer, sauté the beef slices, in two batches, until they are well browned on both sides but rate inside, 3-4 minutes. Transfer the seared meat to the baking sheet. Turn the heat down slightly.||Add 1 tablespoon of the butter to the pan. When it has melted and started to foam, add the mushrooms, toss to coat them with the fat and season with salt and pepper. Cook, stirring frequently, until they have released their moisture and are a deep, dark brown, 12-15 minutes. About halfway into the process, add the sliced shallots and 1 tablespoon butter, and stir to combine.||While the mushrooms cook, add the noodles to the boiling water, and cook until just done, about 10 minutes. Drain the noodles, and toss with the remaining 2 tablespoons butter. Set aside.||When the mushrooms and shallots are soft and caramelized, deglaze the pan with the wine, scraping at all the stuck-on bits on the pan's surface. When the wine has reduced by about half, slowly stir in the cream, followed by the Worcestershire and mustard. Add the meat, along with any accumulated juices, and stir to combine. Cook, stirring occasionally, until the dish is hot and the beef is medium-rare, 2-3 minutes. Taste and adjust the seasonings.||Serve the noodles under or alongside the stroganoff; sprinkle stroganoff with parsley."
},
{name: "Beer-braised Beef and Onions",
cat: "Red Meat",
time: "3 ½ Hours",
ingredients: "1 tablespoon kosher salt (more if needed)<>1 teaspoon black pepper (more for garnish)<>6 Bay Leaves<>2 teaspoons Sweet Paprika (more for garnish)<>4 pounds boneless beef stew meat (cut into 3/2-inch chunks)<>1 tablespoon Unsalted Butter<>1 tablespoon extra-virgin olive oil (more if needed)<>4 Spanish or Large yellow onions (thinly sliced)<>6 sprigs Fresh Thyme<>4 sprigs fresh parsley (+ chopped parsley for garnish)<>1 tablespoon tomato paste<>1 teaspoon Ground Coriander<>1/4 teaspoon ground cinnamon<>1 tablespoon all-purpose flour<>2 cups beef or chicken stock<>1 cup beer",
steps: "In a large bowl, combine salt, pepper, bay leaves and paprika. Toss meat to coat, then cover, refrigerate and marinate at least 2 hours or overnight.||Heat oven to 325 degrees. In a large (8-quart) Dutch oven or other heavy pot, heat butter and oil over medium-high until shimmering. Working in batches, brown beef on two sides until dark and crusty, transferring to a bowl when browned (reserve bay leaves). As you cook, add more oil and adjust heat if necessary to prevent burning.||When all the meat is browned, add onions to the empty pot and raise heat to medium-high. Cook, stirring and scraping up the brown coating on the bottom of the pan as the onions release their liquid.||Continue cooking until onions are deeply golden brown and soft, 20 to 30 minutes, stirring occasionally.||Meanwhile, make a bouquet garni by tying thyme, parsley and reserved bay leaves together with kitchen string (or just throw them in the pot and warn your guests not to eat them).||Push the onions to the sides, then add tomato paste, coriander and cinnamon to the bottom of the pan. Cook, stirring, 1 minute, until paste is darkened and fragrant. Stir in flour, cook another minute, then add stock, beer, 1 cup water and bouquet garni. Return beef and any juices in the bowl to the pot, bring to a simmer, then cover and transfer to oven. Cook until beef is tender, about 2 ½ to 3 hours, turning it over halfway through.||lf the sauce seems thin, remove the meat with a slotted spoon; cover with foil to keep warm. Return pot with liquid to stove and simmer until thickened to taste, 5 to 10 minutes. Return the meat to pot and stir to heat through. Serve from the pot or a platter. Garnish with chopped parsley, flaky sea salt, pepper and paprika. Serve with mustard on the side."
},
{name: "Pot Roast",
cat: "Red Meat",
time: "3 Hours",
ingredients: "3 pound boneless beef chuck roast<>Kosher salt<>Ground black pepper<>3 tablespoons canola oil<>4 tablespoons butter<>2 medium red onions (cut into quarters)<>4 carrots (peeled) cut into 2-inch pieces<>3 stalks celery (cut into 2-inch pieces)<>1 rutabaga (peeled) and cut into 12-16 pieces (a pound)<>8 cremini mushrooms (halved)<>2 parsnips (peeled) and cut into 2-inch pieces<>1 head garlic (top cut off to expose cloves)<>3/4 cup tomato paste<>2 bay leaves<>3 sprigs rosemary<>3/2 cups red wine (preferably) carbernet<>4 cups beef broth",
steps: "Heat oven to 340 degrees. Season meat generously with salt and pepper. Heat oil in a large Dutch oven, or other heavy roasting pan with a lid, over medium-high heat. Sear the meat until a dark crust forms (3 to 4 min per side). Remove meat to a plate.||Reduce heat to medium and add butter to the pan. Melt the butter and add the vegetables, stirring frequently and scraping the bottom of the pot, until the vegetables start to color (8 to 10 minutes).||Add tomato paste and cook, stirring frequently, until it darkens slightly, about 5 minutes.||Add bay leaves, rosemary and wine and cook, stirring occasionally, until liquid is reduced to a thick gravy consistency, 5 to 7 minutes.||Return meat to the pot. Add broth, then cover the pot and transfer to the oven. Cook for 2 hours 20 minutes.||Let roast sit at room temperature for at least 10 minutes. Remove meat to a cutting board to slice. Discard bay leaves and rosemary stems. Squeeze any garlic cloves remaining in their skins into the stew and discard the skins. Serve slices of meat in shallow bowls along with the vegetables and a generous amount of cooking liquid ladled over top."
},
{name: "Geraldine's Pot Roast",
cat: "Red Meat",
time: "3 ½ Hours",
ingredients: "4-5 pound brisket<>Salt<>Ground black pepper<>All-purpose flour<>4 tablespoons olive oil<>2 cups onions (diced)<>5 Cloves garlic (minced)<>3 cups tomatoes (Peeled, seeded, diced)<>1 teaspoon dried oregano<>2 cups red wine<>3/2 cups beef stock<>1 cup green olives (pitted & chopped)<>3/2 teaspoons Dijon mustard<>2 tablespoons tomato paste",
steps: "Season the brisket with salt and pepper and dust it with flour. In a large, heavy pot or Dutch oven with a tight lid, heat 3 tablespoons of the oil over high heat. Add the brisket and brown on all sides. Transfer the meat to a plate.||Add the remaining tablespoon of oil to the pot and reduce the heat to medium low. Add the onions and garlic and cook, stirring, until the vegetables are softened, 3 to 5 minutes. Add the tomatoes, oregano, red wine and stock and bring to a boil.||Return the meat to the pot, reduce the heat and simmer, covered, for 2 hours. Stir in the olives, mustard and tomato paste, and simmer for an additional hour, until the meat is very tender.||Transfer the meat to a platter. If the sauce in the pot seems too watery, simmer, uncovered, until it thickens slightly. Season the sauce with the salt and pepper and pour over the meat. Serve immediately."},
{name: "Soy-Ginger Flank Steak",
cat: "Red Meat",
time: "45 Minutes",
ingredients: "1 tablespoon vegetable or canola oil<>3/2 tablespoons peeled ginger (finely grated)<>1 tablespoon garlic (minced)<>2/3 cup soy sauce (low sodium)<>1/2 cup soy sauce and 3 tablespoons water (Alternative)<>1/2 cup lightly packed brown sugar (light or dark)<>1/2 teaspoon red pepper flakes (Optional)<>2.5-3.0 pound flank steak<>Ground black pepper<>Scallions (thinly sliced) of white & (Optionally) light green parts<>lime wedges (for serving)<>cooked rice (for serving)",
steps: "Preheat the broiler.||Heat the oil in a small saucepan over medium heat. Add the ginger and garlic and cook, stirring, until you can really smell everything and the garlic turns golden, about 3 minutes. Add the soy sauce, brown sugar, and red pepper flakes (optional). Increase the heat to medium-high and let the soy glaze simmer until slightly reduced and syrupy, stirring occasionally, about 5 minutes. Set the glaze aside to cool for about 5 minutes.||Season the flank steak lgihtly with black pepper. Brush the top side of the flank steak with some of the soy glaze, then broil it for 4 minutes. Using tongs, turn the steak, then brush the second side with the glaze.Broil the glank steak until it is done to your liking, about 4 minutes longer for medium-rare. Transfer the steak to a cutting board and let it sit for 5 minutes. Meanwhile, bring the remaining soy glaze to a simmer over low heat.||Thinly slice the flank steak across the grain and brush the slices with some of the reheated soy glaze. Transfer the sliced steak to a platter and scatter the scallions, if using, on top. Arrange the lime wedges on the edge of the platter for people to squeeze over their steak if they like. Put the rest of the soy glaze in a small pitcher or bowl to serve at the table for drizzling over the rice."
},
{name: "Ground Lamb Pulao",
cat: "Red Meat",
time: "45 Minutes",
ingredients: "2 cups basmati rice<>3/2 pounds ground lamb (or beef)<>1 teaspoon ghee<>unsalted butter (Alternative 1)<>or Extra-Virgin olive oil (Alternative 2)<>4 garlic cloves (peeled and grated)<>2 tablespoons grated fresh ginger<>3/2 teaspoons garam masla<>1/2 teaspoon red chile powder<>1/2 teaspoon black pepper<>2 teaspoons kosher salt<>3 tablespoons lime juice<>1/2 teaspoon ground turmeric<>1 bunch scallions (about 6) trimmed and thinly sliced<>1/4 cup loosely packed fresh mint leaves",
steps: "Check the rice and discard any debris. Place the rice in a fine-mesh sieve and rinse under running water until the water runs clear. Place the rice in a bowl, cover with water by 1 inch, and soak for 30 minutes.||As the rice soaks, cook the lamb: Place a medium saucepan with a heavy lid or a Dutch oven over medium heat. When the saucepan is hot, break the lamb into chunks, and cook until the fat renders, about 2 minutes. Drain most of the fat, leaving behind 1 to 2 teaspoons, and continue to cook the lamb until it browns, another 2 minutes.||Add the ghee and heat over medium until it melts, 30 to 45 seconds. Add the garlic and ginger and saute for 1 minute.||Add the garam masala, chile powder, black pepper and 1 teaspoon salt and saute until the spices are fragrant, 1 minute. Add 1 tablespoon lime juice and stir until the flavors come together, about 1 minute.||Transfer the lamb mixture to a large bowl and keep warm (Such as transferring it to a 250-degree oven). Clean the saucepan and wipe dry.||Drain the soaked rice. Add to the same saucepan and cover with water by 1 inch. Stir in 1 tablespoon lime juice, the turmeric and the remaining 1 teaspoon salt. Bring to a boil over medium heat, then cover, and reduce heat to a simmer until the rice absorbs all the water, about 10 minutes. (Do not stir the rice as it ccoks, or the grains might break.) Remove the saucepan from heat, and let sit, uncovered, for 5 minutes.||Stir the rice into the cooked Iamb mixture, then drizzle with the remaining 1 tablespoon lime juice. Fold the scallions and mint into the rice, and serve immediately."
},
{name: "Thin Pan-Seared Pork Chops",
cat: "Red Meat",
time: "30 Minutes",
ingredients: "PORK CHOPS and BRINE<>1/2 cup kosher salt<>1/4 cup brown or granulated sugar<>2 bay leaves<>1 teaspoon coriander seeds<>12 black ppercorns (lightly crushed)<>6 allspice berries (lightly crushed)<>8 thin bone-in pork chops (4-5 ounces each)<>Extra-virgin Olive Oil<>HERB SALAD<>2 tablespoons lemon juice<>1/2 teaspoons grated lemon zest<>3 tablespoons extra-virgin olive oil<>Salt<>Black Pepper<>5 ounces baby arugula (4 cups)<>Mixture of arugula, parsley leaves, mint leaves, and (optionally) pecorino cheese (Alternative)",
steps: "Prepare the brine: In a nonreactive large bowl or large deep baking dish, combine salt, sugar, bay leaves, coriander, peppercorns and allspice. Stir in 8 cups cold water to dissolve salt and sugar.||Add pork chops to brine, making sure they are well submerged, and refrigerate. Leave chops in brine for 1 to 2 hours. Remove from brine, pat dry and bring to room temperature. Discard brine.||Make the dressing for the herb salad: Whisk together lemon juice, zestt and olive oil. Season with salt and pepper and set aside.||Put 2 large cast-iron skillets over medium-high heat and film each pan lightly with oil. (Alternatively, use a large cast-iron griddle or ridged stovetop grill.) When oil is hot, add chops in one layer without crowding.||Cook for about 4 minutes, until chops are nicely browned, then turn and cook for about 3 minutes more, until firm to the touch. Transfer to a warm platter.||Put herb salad leaves in a shallow bowl and season lightly with salt. Toss leaves with half the dressing, just to coat. Place dressed salad on top of pork chops. Drizzle remaining dressing over the top, add shavings of Pecorino cheese (if using), and serve."
},
{name: "Skillet Braised Marinated Pork Chops",
cat: "Red Meat",
time: "na",
ingredients: "2 loin pork chops<>3 tablespoons soy sauce<>3 tablespoons dry vermouth (or sherry)<>1 clove garlic (minced)<>3 scallions (chopped)<>ground pepper<>1 tablespoon peanut or vegetable oil<>1/2 cup dry white wine<>coarse salt (to taste)",
steps: "Marinate chops in mixture of soy sauce, garlic, scallions and pepper at least 2 hours (or overnight)||Heat oil in skillet. Remove chops from marinade and brown on both sides. Add marinade and wine. Cover and simmer 30 minutes. Turning once or until pork is whitish-pink in center and tender. Be careful not to overcook. Season with salt and pepper.||Remove chops. Reduce juices in pan and pour over chops."
},
{name: "(Broiled) Grilled Veal Chops",
cat: "Red Meat",
time: "na",
ingredients: "6 tbs olive oil<>6 tbs red wine (or Balsamac)<>2 sprigs rosemary (Chopped)<>ground pepper<>6 3lb veal chops<>Salt<>Lemon wedges<>Garlic (optional)",
steps: "Mix olive oil, red wine, rosemary, and pepper in 9x12 ceramic or glass backing pan.||Rub chops with cloves and drip both sides of veal chops and marinate, covered in refrigerator for 2 hours (turning several times). Remove 15 minutes before looking.||Prepare grill or stove for 15 minutes on high.||Drain veal chops. Salt and place on grill. Cook until golden with black grill marks for 5 minutes on each side. Garnish with lemon wedges."
},
{name: "Grilled Veal with Pancetta, Fava Beans & Pear",
cat: "Red Meat",
time: "na",
ingredients: "2 ounce pancetta or bacon (chopped)<>10 ounce basket pearl onions or 1 cup frozen<>1 teaspoon sugar<>1 cup canned unsalted chicken brother<>1 cup peeled fava beans or frozen lima beans<>2 teaspoons arrowroot<>6 tablespoons sweet marsala<>1 teaspoon fresh marjorem (minced)<>4 6-oz thin-sliced veal loin chops or T-bone steaks",
steps: "Sauté pancetta in heavy large skillet over medium heat until crisp. Using slotted spoon, transfer to paper towels. Reduce heat to low, add onions, sprinkle with sugar and sauté until brown and tender, about 25 minutes.||Transfer onions to bowl. Add broth, beans and arrowroot to skillet. Simmer until beans are tender, about 5 minutes. Using slotted spoons, transfer beans to onions in bowl. Cook liquid until slightly thickened, about 10 minutes. Add 1/4 cup marsala and marjoraml; return onions and beans to liquid (can be prepared 1 day ahead).||Preheat barbecue (medium-high heat). Brush veal with remaining 2 tablespoons of marsala. Season with salt and pepper. Grill until just medium, approximately 3 minutes per side. Transfer veal to plates.||Meanwhile, simmer sauces 3 minutes. Season to tase with salt and pepper, stir in pancetta. Spoon sauce over veal and serve immediately."
},
{name: "Veal Chops with Basil",
cat: "Red Meat",
time: "na",
ingredients: "4 veal chops<>flour (for dredging)<>2 tablespoons olive oil<>1 medium-size onion (sliced)<>1 clove garlic (minced)<>4 tablespoons prosciutto (chopped)<>1/2 cup fresh basil leaves<>1/4 pound mushrooms (sliced)<>1/4-1/2 cup dry white wine<>Coarse salt<>Ground pepper",
steps: "Dredge the chops lightly in flour. In a large frying pan, heat the oil and brown the chop. Remove and set aside. Add onion, garlic, and proscuito and cook until soft.||Return the chops to skillet, overlapping them slightly if necessary. Add the basil and the mushrooms and cook 15-20 minutes or until chops are cooked. They should be pink in the middle.||Remove the chops from the pan. Add wine, salt, and pepper and bring to a boil. Cook 2-3 minutes. Return chop to pan and sprinkle with basil."
},
{name: "Red Wine-Braised Chicken Thighs with Root Vegetables",
cat: "Chicken",
time: "80 Minutes",
ingredients: "8 medium bone-in chicken thighs (3lb), skin removed<>2 tablespoons all-purpose flour<>3/4 teaspoon kosher salt, plus more to taste<>1/2 teaspoon freshly ground black pepper, plus more to taste<>4 tablespoons olive oil (divided)<>14-ounce packaged frozen peeled pearl onions, thawed and patted dry<>2 cups (peeled and diced) carrot and/or parsnip (about 10 ounces)<>2 cups peeled, large-diced celery root, rutabaga, and/or turnip (about 10 ounces)<>3 cloves garlic (minced)<>1 tablespoon tomato paste (+ 1 teaspoon)<>1 tablespoon fresh thyme (chopped)<>3/2 cups dry red wine, (pinot noir or merlot for example)<>2 cups low-sodium chicken broth<>1 bay leaf<>2 teaspoons red wine vinegar<>Fresh flat-leaf parsley, for garnish (optional)",
steps: "In a large bowl, combine the chicken with the flour and 1/4 teaspoon each of the salt and pepper, and toss to coat evenly.||In a large, heavy pot such as a Dutch oven, over medium-high heat, heat 2 tablespoons of the oil until shimmering. Add half of the chicken and cook until golden on both sides, about 3 minutes per side, then transfer to a plate. Repeat with the remaining chicken.||Add the remaining oil to the empty pot, followed by the onions and the diced vegetables and cook, stirring occasionally, softened slightly, about 4 minutes. Add the garlic and cook for 30 seconds more, then stir in the tomato paste and thyme. Add the wine, bring to a boil and cook, uncovered, for about 2 minutes. Add the broth, bay leaf and the remaining 1/2 teaspoon salt and 1/4 teaspoon pepper and return to a boil.||Return the chicken, along with any accumulated juices, to the pot. Reduce the heat to medium-low, cover, and simmer until the chicken is cooked through and the vegetables are tender, about 25 minutes. Using a slotted spoon, transfer the chicken and vegetables to a rimmed serving plate and tent with foil. Increase the heat to high and cook until the sauce is reduced to about 2 cups, 5 to 10 minutes. Discard the bay leaf, then stir in the vinegar, and season to taste with additional salt and pepper, if desired. Pour the sauce over the chicken and vegetables, garnish with the parsley and serve."},
{name: "Roasted Chicken Provencal",
cat: "Chicken",
time: "75 Minutes",
ingredients: "4 chicken legs<>8 bone-in skin-on chicken thighs (Alternatives)<>2 teaspoons kosher salt<>1 teaspoon freshly ground black pepper<>½-¾ cup all-purpose flour<>3 tablespoons olive oil<>2 tablespoons herbes de Provence<>1 lemon (quartered)<>8-10 cloves garlic (peeled)<>4 to 6 medium-size shallots (peeled and halved)<>1/3 cup dry vermouth<>4 sprigs thyme (For serving)",
steps: "Heat oven to 400 degrees. Season the chicken with salt and pepper. Put the flour in a shallow pan, and lightly dredge the chicken in it, shaking the pieces to remove excess flour.||Swirl the oil in a large roasting pan, and place the floured chicken in it. Season the chicken with the herbes de Provence. Arrange the lemon, garlic cloves and shallots around the chicken, then add the vermouth to the pan.||Put the pan in the oven, and roast for 25 to 30 minutes, then baste it with the pan juices. Continue roasting for another 25 to 30 minutes, or until the chicken is very crisp and the meat cooked through.||Serve in the pan or on a warmed platter, garnished with the thyme."
},
{name: "Three Cup Chicken",
cat: "Chicken",
time: "30 Minutes",
ingredients: "3 tablespoons sesame oil<>1 piece of ginger (2-to-3-inch), peeled and sliced into coins, approximately 12<>12 cloves of garlic (peeled)<>4 whole scallions (trimmed and cut into 1-inch pieces)<>3 dried red peppers<>1 teaspoon red-pepper flakes (Alternative)<>2 pounds chicken thighs (boneless or bone-in) cut into bite-size pieces<>1 tablespoon unrefined or light brown sugar<>1/2 cup rice wine<>1/4 cup light soy sauce<>2 cups basil leaves (preferrably Thai)",
steps: "Heat a wok over high heat and add 2 tablespoons sesame oil. When the oil shimmers, add the ginger, garlic, scallions and peppers, and cook until fragrant, approximately 2 minutes.||Scrape the aromatics to the sides of the wok, add remaining oil and allow to heat through. Add the chicken, and cook, stirring occasionally, until it is browned and crisping at the edges, approximately 5 to 7 minutes.||Add sugar and stir to combine, then add the rice wine and soy sauce, and bring just to a boil. Lower the heat, then simmer until the sauce has reduced and started to thicken, approximately 15 minutes.||Turn off the heat, add the basil and stir to combine. Serve with white rice."
},
{name: "Oven-Roasted Chicken Shawarma",
cat: "Chicken",
time: "45 Minutes",
ingredients: "2 lemons (juiced)<>1/2 cup olive oil (+ 1 tablespoon)<>6 cloves garlic (peeled, smashed and minced)<>1 teaspcon kosher salt<>2 teaspoons freshly ground black pepper<>2 teaspoons ground cumin<>2 teaspoons paprika<>1/2 teaspoon turmeric<>A pinch ground cinnamon<>Red pepper flakes (for taste)<>2 pounds chicken thighs (boneless, skinless)<>1 large red onion (peeled and quartered)<>2 tablespcons chopped fresh parsley",
steps: "Prepare a marinade for the chicken. Combine the lemon juice, 1/2 cup olive oil, garlic, salt, pepper, cumin, paprika, turmeric, cinnamon and red pepper flakes in a large bowl, then whisk to combine. Add the chicken and toss well to coat. Cover and store in refrigerator for at least 1hour (up to 12 hours).||When ready to cook, heat oven to 425 degrees. Use the remaining tablespoon of olive oil to grease a rimmed sheet pan. Add the quartered onion to the chicken and marinade, and toss once to combine. Remove the chicken and onion from the marinade, and place on the pan, spreading everything evenly across it.||Put the chicken in the oven and roast until it is browned, crisp at the edges and cooked through, about 30 to 40 minutes. Remove from the oven, allow to rest 2 minutes, then slice into bits.||(Optional) To make the chicken even more crisp, set a large pan over high heat, add a tablespoon of olive oil to the pan, then the sliced chicken, and sauté until everything curls tight in the heat.||Scatter the parsely over the top and serve with tomatoes, cucumbers, pita, white sauce, hot sauce, olives, fried eggplant, feta, rice (or really anything you want to)"
},
{name: "Vinegar Chicken with Crushed Olive Dressing",
cat: "Chicken",
time: "40 Minutes",
ingredients: "3½ pounds bone-in, skin-on chicken parts<>1 teaspoon ground turmeric<>6 tablespoons olive oil<>Kosher salt<>ground pepper<>1/2 cup white wine vinegar<>1½ cups green Castelvetrano olives (crushed and pitted)<>2 cloves garlic (finely grated)<>1 cup parsley, tender leaves and stems, chopped",
steps: "Heat oven to 450 degrees. Place chicken on a rimmed baking sheet and toss with turmeric and 2 tablespoons olive oil, and season with salt and pepper. Make sure chicken is skin-side up, then pour vinegar over and around chicken and place in the oven.||Bake chicken, without flipping, until cooked through and deeply browned all over, 25-30 minutes.||Meanwhile, combine olives, garlic, parsley, the remaining 4 tablespoons olive oil and 2 tablespoons water in a small bowl; season with salt and pepper.||Once chicken is cooked, remove baking sheet from the oven and transfer chicken to a large serving platter, leaving behind any of the juices and bits stuck to the pan.||Make sure the baking sheet is on a sturdy surface, then pour the olive mixture onto the sheet. Using a spatula or wooden spoon, gently scrape up all the bits the chicken left behind, letting the olive mixture mingle with the rendered fat and get increasingly saucy. Pour olive mixture over the chicken, then serve."
},
{name: "Crispy Paremsan Roast Chicken with Lemon",
cat: "Chicken",
time: "75 Minutes",
ingredients: "1 small lemon<>2 teaspoons kosher salt (plus more to taste)<>1 teaspoon black pepper<>1 teaspoon chopped rosemary (plus 4 sprigs)<>Large pinch of red-pepper flakes (optionally, more for serving)<>3½-4 pound whole chicken (patted dry)<>Extra-virgin olive oil (for drizzling)<>1/3 cup finely grated Parmesan",
steps: "Finely grate 1 teaspoon zest from the lemon and place it in a small bowl. (Save the zested lemon for the drippings.) stir in 2 teaspoons salt, pepper, chopped rosemary and red-pepper flakes (if using). Season the chicken inside and out with salt mixture. Let sit at room temperature for 20 minutes or refrigerate uncovered for up to overnight.||Heat oven to 425 degrees. Place chicken, breast-side up, in a large skillet, sheet pan or roasting pan. Stuff cavity of chicken with rosemary sprigs. Drizzle breast with a little olive oil.||Roast chicken for 30 minutes. Sprinkle chicken all over with Parmesan, then continue roasting until bird's juices run clear when skin is pierced with a knife and the skin is golden, 25-30 minutes longer.||Let chicken for 10 minutes. Squeeze juice from the zested lemon, to taste, into the pan drippings and season with more salt and red-pepper flakes if you like. Carve and serve with drippings spooned over the meat."
},
{name: "Bhatti Da Murgh (Indian Grilled Chicken with Whole Spices)",
cat: "Chicken",
time: "1½ hours",
ingredients: "6 whole, bone-in chicken legs (drumsticks with thighs attached, about 4½ pounds)<>6 cloves garlic (about 2 tablespoons, finely grated)<>2 tablespoons ginger (finely grated)<>1 tablespoon white vinegar<>1½ teaspoons ground cayenne (or to taste)<>1½ teaspoons garam masala<>2 teaspoons fine sea salt<>½ cup plain whole milk yogurt<>1½ teaspoon freshly ground black pepper<>½ teaspoon ground clove<>½ teaspoon ground mace<>½ teaspoon ground anise or fennel seeds<>½ teaspoon ground black cardamom (Optional)<>½ teaspoon ground green cardamom<>2 teaspoons cumin seeds<>2 teaspoons coriander seeds<>1½ teaspoons red-pepper flakes<>3-4 tablespoons melted salted butter (as needed for basting)<>Lime wedges (for serving)",
steps: "Pop the joint on each leg: Grasp a drumstick in one hand and a thigh in the other, and bend the joint back until you hear a crack. (This helps the leg cook more evenly)||Using a small knife, make a slash in the meaty part of each drumstick and thigh 2-3 times, going all the way to the bone.||In a large bowl, stir together garlic, ginger, vinegar, cayenne, garam masala and salt. Keep half the mixture in the bowl and set aside; rub remaining mixture all over chicken, getting underneath the skin. Refrigerate for at least 20 minutes (or up to 2 hours) while you prepare the yogurt marinade.||Stir yogurt into the large bowl with ginger-garlic mixture, then stir in black pepper, clove, mace, anise, black cardamom (if using) and green cardamom. Transfer spice-rubbed chicken to yogurt mixture, tossing gently to coat.||Cover and refrigerate chicken for at least 6 hours (preferably overnight).||When ready to cook, prepare the grill for indirect hear. For charcoal grills: Mound coals to one side, allowing for an area of indirect hear. For gas grills: Turn on only a few of the burners and leave the rest off. For ovens: Heat oven to 450 degrees.||Using a mortar and pestle, the flat side of a knife or a spice grinder for a very brief time, crack the cumin, coriander and red-pepper flakes but do not grind; you want a coarse texture here. Sprinkle spice mix onto chicken to coat each piece.||Place a rimmed baking sheet on the unlit side of the grill or in the oven and let heat for 15 minutes. Carefully place chicken on the hot baking sheet and drizzle each piece with a little melted butter. Cover grill, if grilling. Let chicken cook for 25-35 minutes, drizzling with melted butter two or three times. The chicken is done when the skin is dark brown and the juices run clear when pricked with a knife.||(Optional) If you are grilling, you can sear the chicken over direct hear for 1-2 minutes per side just before serving to char the skin.||Serve chicken on a platter, with lime wedges on the side."
},
{name: "Sheet-Pan Miso Chicken with Radishes and Lime",
cat: "Chicken",
time: "45 Minutes",
ingredients: "4 bone-in, skin-on chicken thighs (about 1½ lb total)<>2 tablespoons olive oil<>Kosher salt<>Black pepper<>1 tablespoon ghee or unsalted butter (room temperature)<>1½ teaspoons white miso paste<>1 pound trimmed radishes (if large, halved)<>1 lime (cut in half)<>2 scallions, light green and white parts only (thinly sliced)<>Black or white sesame seeds, for sprinkling (optional)",
steps: "Heat oven to 450 degrees. Place one rack in the middle of the oven and another about 6 inches from the broiler.||On a large baking sheet, drizzle the chicken all over with 1 tablespoon oil, then season all over with salt and pepper. In a medium bowl, mash together the ghee and miso until combined. Lift up the skin on one chicken thigh, carefully creating a space between the skin and meat, and place about 1/2 teaspoon miso-ghee mixture inside. Close the pocket, then lightly press on top of the skin to spread it around. Repeat with remaining chicken thighs, adding 1/2 teaspoon miso-ghee mixture to each. Massage another 1 1/2 teaspoons mixture all over the chicken, leaving about 1 teaspoon miso-ghee mixture remaining in the bowl.||Arrange the chicken skin-side up, evenly spaced apart, and roast on the middle rack for 15 minutes.||In the same mixing bowl, toss the radishes with the remaining miso-ghee mixture and the remaining 1 tablespoon oil. Season with salt and pepper.||After the chicken has roasted for 15 minutes, scatter the radishes around the chicken and cook until radishes are tender and lightly browned and chicken is cooked through (the temperature in the thickest part of the thigh should reach 165 degrees), another 10 to 15 minutes.||If the chicken skin is not as browned as you’d like, broil on the rack near the broiler until the skin is crispy and golden, 1 to 2 minutes.||Squeeze the lime juice over chicken and radishes, then garnish with the scallions and sesame seeds, if using. Divide among plates and serve."
},
{name: "Cornish Game Hen (Glaze)",
cat: "Chicken",
time: "70 Minutes",
ingredients: "1 Rock Cornish Hen<><mark>[A] Apricot Glaze</mark><>1/2 cup apricot jame<>2 tablespoons soy sauce<>2 tablespoons Dijon mustard<>2 tablespoons honey<><mark>[B] Asian Accent</mark><>2 tablespoons soy sauce<>2 tablespoons of chicken broth<>1 teaspoon sesame oil<><mark>[C] Citrus Glaze</mark><>1/4 cup thawed, frozen orange juice concentrate<>2 tablespoons Dijon mustward<>2 tablespoons honey<><mark>[D] Garlic-Herb</mark><>2 tablespoons fresh garlic (finely chopped)<>2 teaspoons fresh thyme (finely chopped)<>2 teaspoons fresh rosemary (finely chopped)<><mark>[E] Lemon-Basil</mark><>1 Lemon<>Butter (melted)<>1 Sprig basil<><mark>[F] Mexican Spiced</mark><>Taco seasoning<>Cooking spray<><mark>[G] Mustward-Herb</mark><>1 tablespoon Dijon mustward<>Dried tarragon<>Basil<>Thyme<>3/4 cup white wine",
steps: "Roast the hens at 375 degrees for about 1 hour.||Add the glazes in the last 15-20 minutes of roasting the Cornish game hens.||When the juices run clear (when a thigh is pierced with a knife) and a meat thermomete registers 170 degrees, the hens are done.||Serve Cornish game hens out of the oven or with the variations detailed below.||<mark>[A] Apricot Glaze</mark>: Mix 1/2 cup apricot jam, 2 tablespoons of soy sauce, 2 tablespoons of Dijon mustard, and 2 tablespoons honey. Brush the apricot glaze over the hens during the last 15 to 20 minutes of roasting.||<mark>[B] Asian Accent</mark>: Mix 2 tablespoons of soy sauce, 2 tablespoons of chicken broth, and 1 teaspoon of sesame oil. Brush the mixture over the hens and pour a little into the cavities before roasting.||<mark>[C] Citrus Glaze</mark>: Mix 1/4 cup of thawed, frozen orange juice concentrate, 2 tablespoons of Dijon mustard, and 2 tablespoons of honey until well-blended. Brush the glaze over the hens during the last 15 to 20 minutes of roasting.||<mark>[D] Garlic-Herb</mark>: Mix 2 tablespoons of minced fresh garlic, 2 teaspoons of finely chopped fresh thyme, 2 teaspoons of finely chopped fresh rosemary, and 2 teaspoons of finely chopped sage. Loosen the breast skin of each hen and rub one-quarter of the mixture under the skin of each bird.||<mark>[E] Lemon-Basil</mark>: Rub the outside of the hens with a cut lemon and brush with melted butter. Place one lemon half and a sprig of fresh basil into each cavity.||<mark>[F] Mexican Spiced</mark>: Rub the outside of the hens with packaged taco seasoning and lightly coat with cooking spray.||<mark>[G] Mustard-Herb</mark>: Coat the outside of each hen with about 1 tablespoon of Dijon mustard. Sprinkle with a mixture of dried tarragon, basil, and thyme. Deglaze the pan after roasting with 3/4 cup of white wine and serve with the pan juices."
},
{name: "Cornish Hens with Lemon & Sage",
cat: "Chicken",
time: "1 Hour",
ingredients: "2 Cornish Hens<>14 fresh leaves (approximately)<>1/2 lemon<>1 clove garlic (minced)<>2 tablespoons olive oil<>Coarse sea salt<>Freshly ground pepper to taste",
steps: "Preheat oven to 450 degrees. Wipe hens dry with paper towels and put a few sage leaves in cavity and under skin covering breast. Rub hens with lemon inside and out, sprinkle with garlic (inside and out). Rub the skin with oil and season to taste with salt and pepper.||Put hens on their sides on a rack and roast for 15 minutes. Turn them on the other side, roast another 15 minutes, then continue to cook hens until golden brown and juices run clear (about 15 more minutes).||Serve hens on 2 individual heated plates."
}/*,
{name: "Grilled Cornish Hens with Mustward and Lemon",
cat: "Chicken",
time: "40 Minutes",
ingredients: "2 Cornish Hens<>1 tablespoon Dijon mustward<>2 tablespoons fresh terragon leaves (+ more for garnish)<>1 clove garlic (minced)<>1/4 cup freshly squeezed lemon juice<>3 tablespoons olive oil<>Coarse sea salt<>Freshly ground pepper to taste",
steps: "Put each hen breast side down on a flat surface and, using poultry shears or a flat knife, split it along the backbone. Open it out and flatten it. Turn it over and cut off wing tips.||Combine mustward, tarragon, garlic, lemon, olive oil, salt and pepper in a shallow bowl. Put hens in the bowl, one at a time, and coat them with the mixture. Allow to marinate at room temperature for 30 minutes, while you preheat grill or broiler.||Grill or broil hens about six inches --- they cook without burning. Basting --- with marinade. Cook them, turning --- for about 10 minutes on each side. The --- should be golden and the juices clear.||Put hens on 2 warm plates, garnish with sprigs of terragon and serve."
}*/,
{name: "Chicken and Rcie with Scallion-Ginger Sauce",
cat: "Chicken",
time: "45 Minutes",
ingredients: "3/2 cups short-grain white rice (preferrably sushi rice)<>2 cups chicken broth<>1 3-inch piece of ginger, peeled and grated (about 3 tablespoons)<>4 chicken breasts (boneless, skinless) totaling 2lb<>Kosher salt and pepper<>1/4 cup vegetable oil<>6 scallions (trimmed and thinly sliced)<>2 tablespoons unseasoned rice vinegar<>1 jalapeno (halved, seeded, then thinly sliced)<>2 teaspoons toasted white sesame seeds<>1 teaspoon sesame oil<>1/2 teaspoon granulated sugar",
steps: "Place rice in a fine-mesh sieve and rinse under cold water, shaking gently, until the water runs clear. In a medium saucepan, combine rice, broth and 1 tablespoon grated ginger. Season chicken all over with salt and pepper and place on top of rice mixture. Cover and bring mixture to a boil over high. Once mixture comes to a boil, reduce heat to medium-low and simmer until rice is plump, broth is absorbed and chicken is cooked through, 20-22 minutes. Turn off heat and let rest, covered, 10 minutes.||Meanwhile, in a medium bowl, combine the vegetable oil, scallions, vinegar, jalapeno, sesame seeds, sesame oil, sugar and remaining ginger; season with salt and pepper.||Remove chicken from saucepan and slice ½-inch thick crosswise. Fluff rice with a fork and divide among bowls. Top with chicken and scallion-ginger sauce."
},
{name: "Ginger-Scallion Chicken",
cat: "Chicken",
time: "15 Minutes",
ingredients: "2 large scallions (trimmed)<>1/4 cup peanut oil, or neutral oil (grapeseed or sunflower for example), more as necessary<>7/4 pounds boneless skinless chicken thighs or breasts, cut into 1-inch chunks<>1/2 teaspoon kosher salt, as needed<>1 cup cilantro leaves and tender stems (roughly chopped)<>1 (21/2-inch) piece ginger, cut into thin matchsticks (about 3 tablespoons)<>3 tablespoons soy sauce<>Large pinch sugar",
steps: "Cut the scallions in quarters lengthwise, then cut crosswise into 3/2-inch-long pieces. You should end up with thin blades of scallions. Separate out the dark green tops ffom the pale green and white parts. (You don't have to be very thorough; some mixing of colors is fine.)||Heat oil in a wok or 12-inch skillet or over very high heat. When it's shimmering but not smoking, stir in chicken and salt. Cook, stirring almost constantly, until chicken is barely cooked and no longer pink, 3 to 5 minutes. Use a slotted spoon to transfer chicken onto a serving plate, leavint the oil in the pan. Imemdiately scatter cilantro and scallion greens (not whites) over hot chicken.||Return wok to medium-high heat. Make sure there are at least 2 tablespoons oil in the wok. If not, add more oil. Stir in ginger and cook until lightly browned, about 1 minutes. Stir in scallion whites, soy sauce and sugar, and cook for another 30 seconds (if using a skillet, remove from heat). Immediately spoon the contents of the pan evenly over chicken and herbs. Serve right away."
},
{name: "Bake Rice with Chicken and Mushrooms",
cat: "Chicken",
time: "80 Minutes",
ingredients: "2 pounds skinless boneless chicken thighs, cut into 2-inch chunks<>Salt<>Pepper<>2 tablespoons olive oil<>1 large onion, (diced) about 3/2 cups)<>1 sprig thyme (large), plus 1 teaspoon freshly chopped leaves<>1 bay leaf<>1 cup white wine<>2 cups basmati rice (soaked for 20 minutes, rinsed and drained)<>8 ounces king trumpet mushrooms, or a mixture of mushrooms, sliced 1/4-inch thick<>4 cups hot chicken broth<>3 tablespoons unsalted butter<>1 cup frozen peas, cooked for 2 minutes in salted water (optional)<>2 cloves garlic (small), smashed to a paste with a little salt<>3 tablespoons parsley (Roughly Chopped)",
steps: "Put chicken pieces on a baking sheet and season generously with salt and pepper. Set aside. Heat oven to 350 degrees.||Pour olive oil into a 4-quart enamelware Dutch oven or similar heavy pot and set over medium-high heat. Add onions and cook, stirring, until nicely browned, 8 to 10 minutes, then season with salt. Add chicken, thyme sprig and bay leaf, and continue to cook, stirring, for 2 minutes more.||Add wine and simmer briskly until reduced by half, about 5 minutes.||Add rice and a large handful of mushrooms and stir to combine. (Reserve most of the mushrooms for garnish.) Add broth and bring to a simmer. Check broth for seasoning and adjust.||Cover pot and cook for 10 minutes over medium heat. Transfer pot to oven and bake for 20 minutes. Finally, remove from oven and let rest for 10 minutes off heat.||While rice is baking, sauté remaining mushrooms: Melt butter in a large skillet over high heat. Add mushrooms, season with salt and pepper and cook, rapidly stirring, until they have softened and browned, 5 to 7 minutes. Add peas, if using, and heat through. Turn off heat, then add reserved chopped thyme, the garlic and the parsley. Toss to coat well.||Fluff rice, then top with sautéed mushrooms and serve."
},
{name: "Middle Eastern Herb and Garlic Chicken",
cat: "Chicken",
time: "40 Minutes",
ingredients: "6 boneless skinless chicken thighs (about 7/4 pounds)<>6 cloves garlic, grated on a Microplane or minced<>Juice and zest of 2 lemons<>3 tablespoons extra-virgin olive oil, more for serving<>2 tablespoons minced fresh parsley, more for serving<>2 tablespoons minced fresh mint<>1 tablespoon minced fresh thyme<>1 tablespoon minced fresh oregano or marjoram<>3/2 teaspoons kosher salt, more as needed<>1 tablespoon sesame seeds, more for garnish (optional)<>3/4 teaspoon sumac, more for garnish (optional)<>2/3 cup plain Greek yogurt, preferably whole milk yogurt<>1/4 teaspoon ground black pepper",
steps: "Combine chicken with all but 1 teaspoon of the grated garlic (save that teaspoon for the yogurt sauce), the zest and juice of 1 lemon, oil, parsley, mint, thyme, oregano, 1 1/2 teaspoons salt, and the sesame seeds and sumac, if using. Cover and marinate for 15 to 30 minutes at room temperature; you can refrigerate it for up to 24 hours.||Heat grill or broiler. If grilling, cook chicken over high heat until charred in spots, 4 to 7 minutes. Flip pieces and continue grilling until just cooked through, another 4 to 7 minutes. If broiling, arrange a rack 3 to 4 inches from flame. Line a rimmed baking sheet with foil and spread chicken out in a single layer. Broil chicken, turning halfway through cooking, until well colored and charred in spots, 4 to 7 minutes per side. Be careful that it doesn’t burn.||While chicken cooks, place yogurt in a small bowl. Stir in the reserved grated garlic and lemon zest and season to taste with salt. Serve the chicken drizzled with olive oil, remaining lemon juice to taste, black pepper, parsley and sesame seeds and sumac, if using, with the yogurt alongside for dipping."
},
{name: "Miso Chicken in Ginger, Leek, & Scallion Broth",
cat: "Chicken",
time: "1 Hour",
ingredients: "8 boneless, skinless chicken thighs (about 3lb)<>Salt<>Pepper<>2 cloves garlic (large), smashed but not peeled, plus 1/2 teaspoon grated garlic<>1 2-inch piece ginger, peeled and thickly sliced, plus 1 teaspoon grated fresh ginger<>1 small onion (thinly sliced)<>6 cups chicken broth (optional)<>1/4 cup mirin<>4 tablespoons yellow or red miso<>1/2 teaspoon gochugaru (Korean red-pepper flakes)<>2 tablespoons rice wine vinegar<>2 tablespoons granulated sugar<>2 cups leeks, white and tender green parts, chopped into 1/2-inch pieces<>1/2 cup thinly sliced scallions (For garnish)",
steps: "Put chicken thighs in a large pot, seasoning well with salt and pepper on both sides. Add smashed garlic cloves, ginger slices, onion, 6 cups water (or chicken broth, if you prefer) and mirin, and bring to a boil. Reduce heat to a simmer and cook, covered, for 30 minutes, until tender. Remove chicken to a baking dish. Strain broth into a bowl. Place back into the pot, and keep warm. Heat oven to 375 degrees.||In a small bowl, combine miso, gochugaru, grated garlic, grated ginger, vinegar and sugar. Add a little hot broth to thin, then smear mixture over chicken and coat well.||Bake chicken until browned and glazed, about 20 minutes.||While chicken is cooking, bring broth to a simmer, taste and adjust seasoning. Add leeks and cook until just done — soft, but still green, about 5 minutes.||To serve, slice chicken into 1/4-inch pieces and divide among large soup bowls, then ladle broth on top. Spoon any remaining miso mixture from pan over chicken. Garnish with scallions."
},
{name: "Chicken Shawarma",
cat: "Chicken",
time: "3 Hours",
ingredients: "Juice of 2 lemons (about 6 tablespoons)<>1/2 cup olive oil (+1 tablespoon)<>6 cloves garlic (minced)<>1 teaspoon kosher salt<>2 teaspoons freshly ground black pepper<>2 teaspoons ground cumin<>1/2 teaspoon ground turmeric<>Pinch ground cinnamon<>2 teaspoons hot paprika, or more to taste<>Crushed red pepper flakes, or more to taste<>2 pounds chicken thighs (boneless, skinless)<>1 large red onion (about 10 1/2 oz), peeled and cut into 6 wedges<>2 tablespoons chopped flat-leaf parsley (optional)<>FOR SERVING (Optional)<>Pita or naan bread<>Greek salad<>Chopped cucumbers and tomatoes<>Hummus<>Yogurt and cucumber dip<>Kalamata olives<>Feta cheese<>Roasted eggplant<>Cooked rice<>Couscous, such as this Lemon Israeli Couscous<>Hot sauce",
steps: "In a large bowl, combine the lemon juice, 1/2 cup oil, garlic, salt, pepper, cumin, turmeric, cinnamon, paprika, and crushed red pepper flakes and whisk to combine.||Add the chicken to the bowl and toss well to coat. Cover and store in the refrigerator for at least 2 hours and up to 12 hours.||When you’re ready to cook, heat the oven to 425°F (218°C). Slick a rimmed baking sheet with 1 tablespoon oil.||Add the onion wedges to the chicken and marinade and toss to combine.||Place the chicken and onions in a single layer on the baking sheet, letting any excess marinade drip back into the bowl. Discard the marinade.||Roast until the chicken is evenly browned, crisp at the edges, and cooked through, 30 to 40 minutes.||Remove the chicken from the oven and let it rest for a few minutes.||Cut the chicken into 1/2- to 1-inch (1- to 2.5-cm) pieces.Arrange the chicken in a large bowl or on a platter. Scatter the parsley over the top, if using.||If desired, arrange small bowls of extras alongside the chicken and let everyone customize the chicken shawarma to their liking."
},
{name: "Chicken Florentine",
cat: "Chicken",
time: "35 Minutes",
ingredients: "3/2 lb chicken thighs (skinned and boned)<>1/4 cup green olive oil<>1 large, full bulb garlic (chopped)<>2 large onions (chopped)<>1 teaspoon rosemary<>1/2 cup Italian white wine<>1 lb fresh spinach (chopped)<>1 package of frozen chopped spinach (Alternative)<>1 cup fresh Italian prasely (chopped)<>1/2 lemon (squeezed)<>Black pepper to taste<>2 cups water<>1 cup long-grain rice",
steps: "Preheat oven at 350 degrees.||Wash and dry the chicken thoroughly; place it in a shallow, oven-proof glass dish. Add 1/2 of the olive oil and 1/2 of the chopped garlic and onion, and cook for 15 minutes. Sprinkle with rosemary and 1/2 cup of wine. Cover tightly with foil and bake for 25 minutes, or until the sauce has thickened and the chicken is soft, moist, and tender.||In a large covered skillet, sauté the remaining olive oil and garlic and onion over medium heat. After 1 minute, reduce the heat and add 1/2 cup of white wine. Cook slowly over low heat; reduce until slightly thick (about 3-4 minutes). Add the spinach, Italian herb seasoning, parsely, lemon, and black pepper. Cover tightly and cook until al dente (about 6 minutes).||Put exactly 2 cups of water in a separate tightly lidded saucepan, and bring to a fast boil. Add 1 cup of rice and boil for exactly 20 minutes. To serve, pour the cooked spinach in sauce onto a serving platter, and arrange the rice around the outside. Place the pieces of chicken on the bed of spinach. Garnish with thinly sliced tomato, if desired."
},
{name: "Chicken with Tarragon, Shallots, Vinegar",
cat: "Chicken",
time: "na",
ingredients: "1 tablespoon tomato paste<>4 tablespoons fresh parsely<>4 chicken breasts (about 5/4 pounds)<>Salt<>Pepper<>1 tablespoon olive oil<>3 tablespoons shallots<>1 tablespoon garlic (minced)<>1 teaspoon tarragon<>1/2 cup white wine<>4 ripe plum tomatoes (cut into cubes)<>2 tablespoon ted wine vinegar<>4 tablespoons capers (drained)",
steps: "Sprinkle chicken with salt and pepper.||Heat oil in skillet.||Add chicken and sauté over medium heat for 5 minutes.||Add shallots and garlic, cook briefly.||Add tarragon and all the rest but parsely.||Stir to dissolve brown particles (Blend Well).||Bring to a boil, then simmer for 5 minutes.||Serve with rice."
},
{name: "Fippy Chicken",
cat: "Chicken",
time: "na",
ingredients: "Oranges<>Breadcrumbs<>Chicken Breasts<>Honey-Mustward<>Soy sauce<>Orange Juice<>Garlic powder<>Pepper<>Tarragon<>White wine",
steps: "Create marinade by combining orange juice, soy sauce, honey mustard, garlic powder pepper, white wine.||Dip chicken in marinade, then breadcrumbs. Repeat.||Put in baking dish, pour in marinade.||Slice oranges and put on top of chicken.||Add more to marinade, include breadcrumbs and ehat up in separate pot.||Bake chicken 350 degrees for about 20-25 minutes."
},
{name: "Roast Chicken with Garlic",
cat: "Chicken",
time: "na",
ingredients: "7/4 pound roasting chicken<>1 lemon (cut in half)<>1 head garlic (separated in cloves)<>1/2 cup water<>2 tablespoons extra-virtin olvie oil",
steps: "Preheat oven to 400 degrees. Wipe chicken dry with paper towels. Remove loose fat from inside cavity. Squeeze lemon juice on skin and inside cavity.||Arrange hcicken in roastin pan. Place the garlic around chicken and pour in water. Sprinkle chicken with oil.||Roast 45-60 minutes or until chicken is cooked, basting frquently. Garlic should roast without bruning, once water is evaporated. If garllic browns too fast, add a little more water.||Serve chicken, surrounded by garlic on platter."
},
{name: "Brined Chicken",
cat: "Chicken",
time: "75 Minutes",
ingredients: "FOR BRINE<>1/2 cup kosher salt<>7/4 cups sugar<>1 cup honey<>3 sprigs of parsely, dill, thyme, tarragon, sage<>1 sprig rosemary<>1 tablepsoon mustard seeds<>1 tablespoon fennel seed<>1 cinnamon stick<>2 large bay leaves<>4 cloves<>1/2 tablespoon juniper berries<>1/2 tablespoon crardamom peas/pocas<>1 tablespoon black peppercorn<>1 lemone (halved and squeezed lightly<>3 star anise<>1/2 tablespoon whole all spiced<>FOR THE CHICKEN<>7/4 pound chicken<>1 cup carrots (sliced)<>1 cup celery (sliced)<>1 cup onion (sliced)<>2 tablespoons unsalted butter (melted)",
steps: "In large stockpot or roasting pan, palce 1 gallon water. Bring to boil and remove from heat. Add all ingredients for brine and stir. Coolt or oom temperature.||Add chicken to pan. Cover and refrigrerate overnight.||Drain chicken well and discard brine. Cut off and discard wing tips. Preheat oven to 350 degrees. In a roasting pan, place carrots, celery, and onion. Place chicken on top of vegetables. Brush chicken with melted butter.||Roast chicken until thigh joint temperature reaches 150 degrees (about 1 hour). Baste with pan juices at least every 15 minutes. Watch carefully to avoid burning; if parts become well-browned, cover with foil. When chick is done, remove from oven, and allow it to rest 10 minutes before carving."
},/*
{name: "Brined Chicken (2)",
cat: "Chicken",
time: "75 Minutes",
ingredients: "1 cup chicken stock<>1/2 cup Japanese soy sauce<>7 tablespoons sugar<>1 tablespoon cornstarch<>1 tablespoon water<>2 chicken breasts (boneless, skinless)<>2 tablespoons vegetable oil",
steps: "steps"
},*/
{name: "Nobu's Chicken Teriyaki",
cat: "Chicken",
time: "na",
ingredients: "1 cup chicken stock<>1/2 cup Japanese sooy sauce<>7 tablespoons sugar<>1 tablespoon corn starch<>1 tablespoon water<>2 whole chicken breasts (boneless, skinless)<>2 tablespoons vegetable oil",
steps: "Bring the stock, soy sauce and sugar to a boil in a small saucepan. Lower the heat and simmer for 2 minutes. Mix together the cornstarch and the water and whisk into the teriyaki base. Bring back to a boil and simmer for 2 more minutes. Remove from the heat.||Prick holes in the chicken with the tines of a fork. Pour the sauce over the chicken breasts and marinate, turning occasionally, for 6 hours, or overnight.||Heat the grill. Scrape the excess sauce off the chicken and reserve. Brush the grill with oil. Grill the chicken for 5 minutes. Turn and baste with the sauce. Continue to turn and baste, using as much sauce as desired, until the juices run clear when pricked with a knife. About 12 to 15 minutes."
},
{name: "Peruvian Chicken",
cat: "Chicken",
time: "2 Hours",
ingredients: "3.5 lb whole chicken (spatchcock recommended)<>2 tbsp avocado or olive oil<>2 tbsp ajiamarillo paste<>3/2 tbsp lime juice<>3 cloves garlic (large), pressed or minced<>2 tsp kosher salt<>1 tsp ground cumin<>1 tsp dried oregano<>1 tsp freshly ground black pepper<>Cilantro jalapeno sauce (for serving, optional)",
steps: "While it's not required, I highly recommend you spatchcock the chicken. All this means is you cut the backbone out so it lays flat on the roasting pan. Spatchcock chicken cooks more evenly, more quickly, and is much easier to carve. My Spatchcock Chicken post shows you how do to this.||In a small bowl, mix together the avocado oil, aji amarillo paste, lime juice, garlic, salt, cumin, oregano, and black pepper.||Place the chicken on a sheet pan and pat the chicken dry with a paper towel. Then rub the marinade all over the chicken. Let sit at room temperature for one hour.||Alternatively, you can marinate this up to 24 hours in advance in the fridge. Note: never leave meat out of the fridge for more than 2 hours.||15 minutes before cooking, preheat the oven to 425F.||Roast the chicken for 40-45 minutes, basting the chicken in its own juices after 30 minutes, and again at 40 minutes. When the chicken is done, the breast should register at 160F when measured with a thermometer.||Let the chicken rest for 5-10 minutes after roasting, so the juices don't run out while carving. Enjoy!"
},
{name: "Chicken Breast w Mushrooms & Capers",
cat: "Chicken",
time: "na",
ingredients: "4 chicken breasts (boneless, skinless), around 3/2 pounds<>Salt and freshly ground pepper for taste<>2 tablespoons olive oil<>1/2 cup onion (finely chopped)<>1 teaspoon garlic (finely chopped)<>1 teaspoon chopped fresh rosemary or 1 teaspoon dried<>1 pound small mushrooms (if large, cut in quarters)<>2 tablespoons red wine vinegar<>4 tablespoons capers (drained)<>1/2 cup chicken broth (Fresh or Canned)<>1 tablespoon tomato paste<>4 tablespoons parsely (chopped)",
steps: "Cut the chicken in lite-sized pieces. Sprinkle the chicken with salt, pepper and flour.||Heat the oil in a heavy-bottomed skillet. Add the chicken breasts. Sauté them over medium-high heat, turning often, until lightly browned, about 5 minutes.||Add the onion, garlic, rosemary and mushrooms. Cook stirring about 5 minutes.||Pour off the fat and add the vinegar, stirring to dissolve the brown particles clinging to the skillet. Add the capers, broth and tomato paste and blend well. Bring to a boil, cover and simmer 5 minutes. Add the parsely and stir to coat the chicken well. Serve."
},
{name: "Chicken Skillet w Orzo, Dill, & Fetas",
cat: "Chicken",
time: "35 Minutes",
ingredients: "2 lemons<>5 tablespoons olive oil<>3 cloves garlic (smashed)<>1 teaspoon kosher salt<>1 teaspoon black pepper<>2 pounds chicken drumsticks or bone-in thighs<>1 yellow onion (peeled and chopped)<>2 cups orzo<>3 cups chicken broth or water<>2 small or 1 large thin-skinned (English) cucumbers (chopped)<>5 ounces feta, crumbled (about 7/4 cups)<>2 tablespoons fresh dill (chopped)<>Castelvetrano or other green olives (For serving)",
steps: "Cut one of the lemons into wedges and set aside. Juice the remaining lemon and combine with 3 tablespoons olive oil, garlic, salt and pepper, in a large resealable plastic bag or in a bowl, along with the chicken pieces. Seal and shake the bag (or stir in the bowl) to coat. Set aside for 30 minutes, or refrigerate up to overnight.||Heat the remaining 2 tablespoons olive oil in a large cast-iron skillet over medium-high heat. Remove the chicken from the marinade, letting the excess drip off, and cook until lightly golden all over, turning when the chicken releases easily from the pan, about 12 minutes total. Transfer chicken to a plate and set aside.||Add the onion to the pan and stir to coat with the remaining fat. Decrease heat to medium and cook until soft, about 4 minutes. Stir in the orzo and the broth or water. Cook until the liquid is partly absorbed, stirring occasionally, about 5 minutes. Top with the chicken legs and cover with a lid or foil. Continue cooking until the orzo is tender, most of the liquid is absorbed, and the chicken is cooked through, 15 to 20 minutes more, depending on the size of your drumsticks or thighs. Remove from the heat and scatter the cucumber, feta and dill over the top. Serve from the skillet with lemon wedges and olives."
},
{name: "Halibut With Brown Butter, Lemon and Sage",
cat: "Fish",
time: "30 Minutes",
ingredients: "3/2~ pounds halibut fillets (or other firm white-fleshed fish), cut into 4 pieces<>Salt<>Black pepper<>2 tablespoons olive oil<>4 tablespoons butter (unsalted)<>12-15 fresh sage leaves<>2 tablespoons lemon juice (freshly squeezed)<>1/4 cup coarse homemade bread crumbs (toasted)<>2 tablespoons parsley (finely chopped)<>Lemon wedges (for serving)",
steps: "Season fish on both sides with plenty of salt and pepper.||Pour oil into a large, heavy skillet (preferably cast iron or nonstick) and set over medium-high heat. When oil is hot (but not smoking), swirl to evenly coat the pan, then add fish in a single layer. Let cook undisturbed for 3 to 4 minutes, until first side is nicely browned. Adjust the heat as needed to produce a steady sizzle and prevent scorching.||Flip and cook fish for about another 3 minutes, until just done. (To test for doneness, use a fork to gently probe the flesh: it should flake easily.) Transfer cooked fish to a warm platter or serving plates.||Make the sauce: Place skillet back on the stove over medium-high heat. Add butter and sage leaves. Cook butter, swirling the pan, until foamy and just beginning to brown, about 1 minute. Turn off heat and stir in lemon juice.||Spoon butter sauce and sage leaves over fish. Sprinkle with bread crumbs and parsley. Serve immediately, with lemon wedges."
},
{name: "Trout With Chive Butter",
cat: "Fish",
time: "10 Minutes",
ingredients: "4 whole trout (butterflied)<>Fine sea salt, to taste<>1 clove garlic (finely grated or minced)<1/2 teaspoon fresh lemon or lime juice (more to taste)<>1/8 teaspoon ground black pepper<>4 tablespoons unsalted butter (cubed and softened)<>1 tablespoon chives (minced), more for serving<>Trout roe, salmon roe or capers, for serving (optional)",
steps: "Heat the broiler. Place trout, skin side down, on a rimmed baking sheet. Sprinkle with salt.||In a mini food processor, or using a mortar and pestle or a bowl and a fork, stir together garlic, lemon juice, pepper and a pinch of salt. Add softened butter and chives and mash or process until well mixed.||Broil trout until just opaque, 2 to 5 minutes depending upon your broiler.||Drop spoonfuls of butter on top of the fish; it will melt immediately. Top with more chives and with roe or capers, and a little more lemon juice if you like."
},
{name: "Shrimp Scampi",
cat: "Fish",
time: "25 Minutes",
ingredients: "1 pound large shrimp (peeled and deveined)<>3 tablespoons extra-virgin olive oil<>1 tablespoon lemon zest, plus 1 tablespoon juice (from 1 lemon)<>1/2 teaspoon red pepper flakes<>Kosher salt<>Black pepper<>4 cloves garlic (minced)<>2 tablespoons unsalted butter<>1 cup orzo<>1/3 cup dry white wine<>2 cups boiling water<>2 cups seafood stock (Alternative 1)<>2 cups chicken stock (Alternative 2)<>3 tablespoons parsley (finely chopped)",
steps: "In a medium bowl, stir together shrimp, 1 tablespoon olive oil, lemon zest, red-pepper flakes, 1/2 teaspoon salt, 1/4 teaspoon pepper and half the garlic. Set aside to marinate. (This step can be done up to 1 hour in advance.)||Add butter, remaining olive oil and remaining garlic to a medium skillet set over medium heat. When the butter starts to bubble, add the orzo and 1/2 teaspoon salt and cook, stirring often, until the orzo is toasted, about 2 minutes, adjusting the heat as necessary to prevent the garlic from burning. Carefully add the wine — it will bubble — and stir until absorbed, about 1 minute. Stir in water, reduce heat to low, cover, and cook until orzo is al dente, about 12 minutes.||Add the shrimp in a snug, even layer on top of the orzo, cover, and cook until all the shrimp is pink and cooked through, 2 to 4 minutes. Remove from heat and let sit, covered, 2 minutes.||Sprinkle with parsley and lemon juice, season with salt and pepper, and serve immediately."
},
{name: "Roasted Salmon With Miso Rice and Ginger-Scallion Vinaigrette",
cat: "Fish",
time: "30 Minutes",
ingredients: "1/4 cup white or sweet miso<>3/2 cups basmati or other long-grain rice<>4 salmon fillets (each 6-ounce, skin-on)<>2 tablespoons extra-virgin olive oil<>Kosher salt<>Black pepper<>1/4 cup low-sodium soy sauce<>1/4 cup scallions (chopped), plus more for garnish<>1 tablespoon distilled white vinegar or unseasoned rice vinegar<>1 tablespoon fresh ginger (minced)<>4 cups cabbage (finely shredded), such as green, Napa or savoy (about 8 ounces)<>Roasted sesame oil, for serving",
steps: "Heat oven to 425 degrees. In a medium saucepan, whisk miso with 2 1/4 cups water until dissolved. Stir in rice and bring to a boil. Cover, reduce heat to low and cook until all of the liquid is absorbed and rice is tender, about 15 minutes. Remove from heat and let stand for 5 minutes. Fluff rice with a fork (it will be a little sticky).||On a rimmed baking sheet, rub salmon all over with olive oil, season with salt and pepper and arrange skin-side up. Roast until fish is just opaque and cooked to medium, 8 to 10 minutes.||In a small bowl, combine soy sauce, scallions, vinegar and ginger, and season with salt and pepper.||Divide miso rice and cabbage among bowls. Top with salmon, ginger-scallion vinaigrette and sesame oil."
},
{name: "Salmon With Anchovy-Garlic Butter",
cat: "Fish",
time: "25 Minutes",
ingredients: "3 tablespoons unsalted butter (softened)<>4 anchovy fillets (minced)<>1 clove fat garlic, minced (or 2 small ones)<>1/2 teaspoon coarse kosher salt<>Freshly ground black pepper<>4 salmon fillets (each 6-8 ounce, skin-on)<>2 tablespoons drained capers (patted dry)<>1/2 lemon<>Fresh parsley (chopped), for serving",
steps: "Heat oven to 400 degrees. In a small bowl, mash together butter, anchovies, garlic, salt and pepper.||In a large ovenproof skillet, melt about half the anchovy butter. Add fish, skin side down. Cook for 3 minutes over high heat to brown the skin, spooning some pan drippings over the top of the fish as it cooks. Add capers to bottom of pan and transfer to oven. Roast until fish is just cooked through, 8 to 10 minutes.||Remove pan from oven and add remaining anchovy butter to pan to melt. Place salmon on plates and spoon buttery pan sauce over the top. Squeeze the lemon half over the salmon and garnish with chopped parsley. Serve."
}/*,
{name: "Roast Salmon with Spicy Soy Sauce",
cat: "Fish",
time: "20 Minutes",
ingredients: "2 tablespoons peanut oil<>1½-2 pounds salmon fillets (in 4 pieces)<>Salt<>Freshly ground black pepper<>1 tablespoon sesame oil<>1 tablespoon garlic (slivered)<>2 dried red chilies<>1 tablespoon soy sauce<>1/2 cup scallions (chopped)<>1/4 cup cilantro (chopped) (Alternative)",
steps: "Preheat oven to 500 degrees. Place 12-inch nonstick ovenproof skillet over medium high heat. When not, add 1 tablespoon peanut oil; swirl. Season salmon with salt & pepper and place skin side up in skillet. When salmon has browned (about 1 minute), flip over and transfer to oven.||Combine remiaing peanut oil in small saucepan with sesame oil, garlic & chillies, and turn heat to medium. Cook gently shaking pan until garlic colors lightly, about 5 minutes. Turn off heat and remove chilies. When sauce cools ___||Salmon will be medium-rare after 6 minutes ___ oven. Cook longer if you like. ___ plate. ____ with oil, scallions and serve."
}*/,
{name: "Salty-Sweet Barbecue Salmon and Broccoli",
cat: "Fish",
time: "30 Minutes",
ingredients: "1 pound broccoli florets, cut into 1-inch pieces (about 8 cups)<>12 scallions (trimmed and halved crosswise)<>1 (1-inch) piece fresh ginger, peeled and julienned (about 1 1/2 tablespoons)<>1/4 cup safflower or canola oil<>Kosher salt<>Black pepper<>2 tablespoons yellow onion (finely chopped)<>1 tablespoon garlic (minced)<>1 teaspoon tomato paste<>3 tablespoons turbinado sugar<>2 tablespoons light brown sugar (Alternative)<>6 tablespoons oyster sauce<>2 tablespoons unseasoned rice vinegar<>1 tablespoon low-sodium soy sauce<>4 salmon fillets (6-ounce, skin-on)<>Steamed rice, for serving",
steps: "Heat oven to 450 degrees. On a rimmed baking sheet, combine broccoli, scallions, ginger and 2 tablespoons oil. Season with salt and pepper, and toss to coat. Spread in an even layer and roast until softened, about 15 minutes.||While the broccoli mixture roasts, prepare the oyster barbecue sauce: In a small saucepan, heat the remaining 2 tablespoons oil over low. Add onion and garlic, and cook until softened, about 2 minutes. Add tomato paste and cook, stirring frequently, for 1 minute. Add sugar and cook, stirring, until sugar dissolves and the mixture darkens slightly, about 3 minutes. Stir in 1/2 cup water (be careful, as the mixture may splatter a little), then the oyster sauce, vinegar and soy sauce. Bring to a simmer. (The sugar may seize, but keep stirring; it will dissolve.) Cook, stirring, until sauce is thickened, about 5 minutes. Season generously with pepper. Remove 1/2 cup and set aside for passing at the table.||Stir the roasted broccoli. Season salmon with salt and arrange on top of the broccoli. Liberally brush salmon all over with half of the remaining oyster barbecue sauce in the saucepan. Roast until the vegetables are caramelized and the salmon is cooked through, 8 to 10 minutes, basting salmon after 5 minutes with the barbecue sauce.||Divide salmon and vegetables among plates. Serve with steamed rice and the reserved barbecue sauce."
},
{name: "Five-Ingredient Creamy Miso Pasta",
cat: "Pasta",
time: "20 Minutes",
ingredients: "Kosher salt<>16 ounces spaghetti, linguine or bucatini<>6 tablespoons unsalted butter<>3 tablespoons miso (white or red)<>4 ounces Parmesan, finely grated (1 packed cup)<>Kizami nori, furikake or thinly sliced seaweed snacks, for garnish (optional)",
steps: "Bring a large pot of salted water to a boil. Add the pasta and cook, stirring occasionally, until al dente. Reserve 1 1/2 cups pasta water, then drain the pasta.||Add the butter, miso and 1 1/4 cups pasta water to the pot and whisk over medium heat until miso breaks down and liquid is uniform, 1 to 2 minutes. Add the pasta and Parmesan and cook, stirring vigorously with tongs until cheese is melted and sauce emulsifies. (The key word here is “vigorously.” To achieve a silky smooth pasta instead of a gloppy one, put your cacio e pepe skills to work.)||Divide among shallow bowls and sprinkle with nori or furikake, if using."
},
{name: "Fast Spaghetti Bolognese",
cat: "Pasta",
time: "30 Minutes",
ingredients: "Kosher salt<>Black pepper<>2 tablespoons olive oil<>1 medium yellow onion (finely chopped)<>2 garlic cloves (finely chopped)<>1/2 pound ground beef (preferably 20 percent fat), pork or dark meat turkey<>12 ounces spaghetti, pappardelle or other long pasta<>1/4 cup tomato paste<>2 teaspoons Worcestershire sauce<>Parmesan (Grated), for serving",
steps: "Bring a large pot of salted water to a boil. Heat oil in a large skillet over medium-high. Add onion, garlic and 1/2 teaspoon salt and cook, stirring often, until beginning to soften, 3 minutes. Add beef and cook, breaking up with a wooden spoon, until no longer pink, about 3 minutes.||Add pasta to the pot and cook according to package instructions until al dente.||Meanwhile, add tomato paste to skillet and cook, stirring, until darkened, about 1 minute. Add 1 cup water, Worcestershire, 1/2 teaspoon pepper and 1/2 teaspoon salt and simmer until slightly reduced, about 5 minutes.||Using tongs, transfer pasta directly from the pot to the skillet along with 1 cup pasta water. Increase heat to high and simmer vigorously, tossing, until sauce reduces and coats the pasta, about 2 minutes. Season to taste with salt and pepper. Serve with Parmesan."
},
{name: "Mapo Ragù",
cat: "Pasta",
time: "1 Hour",
ingredients: "3 tablespoons neutral oil, like canola<>2 large onions, peeled and sliced<>Pinch of kosher salt, or to taste<>1 pound ground pork<>4 cloves garlic, peeled and chopped<>10-15 frozen cylindrical rice cakes (optional), or rice noodles, or pasta, or steamed rice<>1 inch fresh ginger (peeled and chopped)<>3 tablespoons gochujang (Korean chili-bean paste)<>1 tablespoon low-sodium soy sauce<>1 tablespoon brown sugar<>2 teaspoons Sichuan peppercorns (optional)<>1 bunch kale or any hearty cooking greens (roughly chopped)<>4 scallions (thinly sliced) for garnish",
steps: "Heat the oil in a wok set over medium-high heat. When it shimmers, add the onions and the pinch of salt. Cook, stirring occasionally, until the onions have released their moisture and are starting to brown, approximately 10 minutes. Then turn the heat down to low, and continue to cook, stirring every few minutes, until they have turned golden brown and sweet, an additional 20 minutes or so.||Tip the onions into a bowl, and return the wok to high heat over the stove. Add remaining tablespoon of oil, then the pork, and cook, breaking the meat up with a spoon, until it is just cooked, but not yet browning, approximately 10 minutes. Add the cooked meat to the reserved onions.||If using the rice cakes, put a large pot of salted water over high heat, and bring to a boil.||Return wok to stove over medium heat and cook the garlic and ginger in fat remaining from pork (add an extra splash of neutral oil if necessary). When the garlic and ginger soften, add gochujang, soy sauce, brown sugar and, if using, the Sichuan peppercorns. Add 1/2 cup to 1 cup of water, enough to loosen the gochujang and make a sauce, then return pork and onions to the wok and stir to combine. Adjust seasonings.||Bring sauce to a simmer, and add the chopped greens, then stir to combine and cook until they have started to soften, approximately 5 minutes.||If using rice cakes, place them in the boiling water for 3 to 5 minutes to soften, then drain and add to the sauce. (If not, serve the ragù with steamed rice, rice noodles or pasta.) Garnish with the sliced scallions."
},
{name: "Linguine with Clam Sauce",
cat: "Pasta",
time: "25 Minutes",
ingredients: "Kosher salt<>1 pound linguine or other long pasta, such as linguine fini or spaghetti<>1/4 cup extra-virgin olive oil, plus more for serving (optional)<>5 garlic cloves, thinly sliced<>½-1 teaspoon red-pepper flakes<>1/2 teaspoon dried oregano<>1/2 cup dry vermouth or dry white wine<>2 cans (10-ounce) whole baby clams with their juices<>Black pepper<>2 tablespoons unsalted butter<>2 teaspoons lemon zest (from 1-2 lemons)<>1/2 cup Italian parsley (chopped)<>Lemon wedges, for serving (optional)",
steps: "Bring a large pot of salted water to a boil. Add the pasta and cook according to package instructions until 2 minutes short of al dente (it will finish cooking in the sauce). Reserve 1/2 cup pasta water, then drain pasta.||While the pasta cooks, make your sauce: Heat the oil in a deep-sided 12-inch skillet over medium. Add the garlic, red-pepper flakes and oregano and cook until the garlic is pale golden, 1 to 2 minutes. Add the vermouth and simmer until reduced by half, 3 to 4 minutes. Stir in the clams with their juices and cook until just warmed through, 1 to 2 minutes more. Taste and season with salt and pepper as needed.||Add the cooked pasta directly to the skillet along with the butter and lemon zest and toss until the butter has melted and the pasta is glossy with sauce. If needed, add 1/4 cup reserved pasta water. Stir in half the parsley.||Serve pasta topped with a drizzle of olive oil, if desired, and the remaining parsley. Serve lemon wedges alongside if you like."
},
{name: "Marcella Hazan’s Bolognese Sauce",
cat: "Sauce",
time: "4 Hours",
ingredients: "1 tablespoon vegetable oil<>3 tablespoons butter plus 1 tablespoon for tossing the pasta<>1/2 cup chopped onion<>2/3 cup chopped celery<>2/3 cup chopped carrot<>3/4 pound ground beef chuck (or you can use 1 part pork to 2 parts beef)<>Salt<>Black pepper, ground fresh from the mill<>1 cup whole milk<>Whole nutmeg<>1 cup dry white wine<>3/2 cups canned imported Italian plum tomatoes, cut up, with their juice<>1¼-1½ pounds pasta<>Freshly grated parmigiano-reggiano cheese at the table",
steps: "Put the oil, butter and chopped onion in the pot and turn the heat on to medium. Cook and stir the onion until it has become translucent, then add the chopped celery and carrot. Cook for about 2 minutes, stirring vegetables to coat them well.||Add ground beef, a large pinch of salt and a few grindings of pepper. Crumble the meat with a fork, stir well and cook until the beef has lost its raw, red color.||Add milk and let it simmer gently, stirring frequently, until it has bubbled away completely. Add a tiny grating -- about 1/8 teaspoon -- of nutmeg, and stir.||Add the wine, let it simmer until it has evaporated, then add the tomatoes and stir thoroughly to coat all ingredients well. When the tomatoes begin to bubble, turn the heat down so that the sauce cooks at the laziest of simmers, with just an intermittent bubble breaking through to the surface. Cook, uncovered, for 3 hours or more, stirring from time to time. While the sauce is cooking, you are likely to find that it begins to dry out and the fat separates from the meat. To keep it from sticking, add 1/2 cup of water whenever necessary. At the end, however, no water at all must be left and the fat must separate from the sauce. Taste and correct for salt.||Toss with cooked drained pasta, adding the tablespoon of butter, and serve with freshly grated Parmesan on the side."
},
{name: "Sausage Ragù",
cat: "Sauce",
time: "2 Hours",
ingredients: "1 pound sweet Italian sausage or bulk sausage<>Extra-virgin olive oil<>1 onion (minced)<>1 carrot (minced)<>1 celery stalk (minced)<>1/4 cup flat-leaf parsley (minced), plus extra for garnish<>1 can (28-ounce) whole tomatoes, preferably San Marzano, with its juice<>1 sprig fresh thyme (large)<>1 sprig fresh rosemary (large)<>3 tablespoons tomato paste<>Salt<>Ground black pepper<>1 pound tubular dried pasta such as mezzi rigatoni, paccheri or penne<>Freshly grated Parmesan cheese, for garnish (optional)",
steps: "With the tip of a small, sharp knife, slit open the sausage casings. Crumble the meat into a wide, heavy skillet or Dutch oven and set over medium-low heat. If the meat is not rendering enough fat to coat the bottom of the pan as it begins to cook, add olive oil one tablespoon at a time until the meat is frying gently, not steaming. Sauté, breaking up any large chunks, until all the meat has turned opaque (do not let it brown), about 5 minutes.||Add onion, carrot, celery and parsley and stir. Drizzle in more oil if the pan seems dry. Cook over very low heat, stirring often, until the vegetables have melted in the fat and are beginning to caramelize, and the meat is toasty brown. This may take as long as 40 minutes, but be patient: It is essential to the final flavors.||Add tomatoes and their juice, breaking up the tomatoes with your hands or with the side of a spoon. Bring to a simmer, then add thyme and rosemary and let simmer, uncovered, until thickened and pan is almost dry, 20 to 25 minutes.||Mix tomato paste with 1 cup hot water. Add to pan, reduce heat to very low, and continue cooking until the ragù is velvety and dark red, and the top glistens with oil, about 10 minutes more. Remove herb sprigs. Sprinkle black pepper over, stir and taste.||Meanwhile, bring a large pot of salted water to a boil. Boil pasta until just tender. Scoop out 2 cups cooking water, drain pasta and return to pot over low heat. Quickly add a ladleful of ragù, a splash of cooking water, stir well and let cook 1 minute. Taste for doneness. Repeat, adding more cooking water or ragù, or both, until pasta is cooked through and seasoned to your liking.||Pour hot pasta water into a large serving bowl to heat it. Pour out the water and pour in the pasta. Top with remaining ragù, sprinkle with parsley and serve immediately. Pass grated cheese at the table, if desired."
},
{name: "Lemony White Bean Soup With Turkey and Greens",
cat: "Soup & Stew",
time: "45 Minutes",
ingredients: "3 tablespoons olive oil<>1 large onion (diced)<>1 large carrot (diced)<>1 bunch sturdy greens, such as kale, broccoli rabe, mustard greens or collard greens<>1 tablespoon tomato paste<>3/4 teaspoon ground cumin, plus more to taste<>1/8 teaspoon red-pepper flakes, plus more to taste<>1/2 pound ground turkey<>3 cloves garlic (minced)<>1 tablespoon fresh ginger (finely grated)<>1 teaspoon kosher salt, plus more to taste<>1 quart chicken stock<>2 cans (15-ounce) white beans, drained and rinsed<>1 cup chopped fresh, soft herbs, such as parsley, mint, dill, basil, tarragon, chives or a combination<>Fresh lemon juice, to taste",
steps: "Heat a large pot over medium-high for a minute or so to warm it up. Add the oil and heat until it thins out, about 30 seconds. Add onion and carrot, and sauté until very soft and brown at the edges, 7 to 10 minutes.||Meanwhile, rinse the greens and pull the leaves off the stems. Tear or chop into bite-size pieces and set aside.||When the onion is golden, add tomato paste, 3/4 teaspoon cumin and 1/8 teaspoon red-pepper flakes to the pot, and sauté until paste darkens, about 1 minute. Add turkey, garlic, ginger and 1 teaspoon salt, and sauté, breaking up the meat with your spoon, until turkey is browned in spots, 4 to 7 minutes.||Add stock and beans, and bring to a simmer. Let simmer until the soup is thick and flavorful, adding more salt if needed, 15 to 25 minutes. If you like a thicker broth, you can smash some of the beans with the back of the spoon to release their starch. Or leave the beans whole for a brothier soup.||Add the greens to the pot and simmer until they are very soft. This will take 5 to 10 minutes for most greens, but tough collard greens might take 15 minutes. (Add a little water if the broth gets too reduced.)||Stir herbs and lemon juice into the pot, taste and add more salt, cumin and lemon until the broth is lively and bright-tasting. Serve topped with a drizzle of olive oil and more red-pepper flakes, if desired"},
{name: "Roy Choi’s Braised Short-Rib Stew",
cat: "Soup & Stew",
time: "3½ Hours",
ingredients: "4 pounds bone-in short ribs<>1 small bunch scallions (trimmed and roughly chopped)<>3/2 cups soy sauce<>1/4 cup chopped fresh ginger<>1 small yellow onion (roughly chopped)<>1/2 cup garlic cloves, peeled (about 2 heads)<>1/2 cup granulated sugar<>1/2 cup mirin<>1/2 cup fresh orange juice<>1/2 cup apple juice<>1/2 pound shiitake mushrooms, stems reserved for another use (halved or quartered if large)<>1 cup jarred, peeled chestnuts<>1 cup taro, peeled and cut into large dice (about a 3-inch segment)<>1 cup carrots, peeled and cut into large dice (about 2 carrots)<>1 cup butternut squash, peeled and cubed (about half a squash)",
steps: "Put short ribs in a bowl, and cover with water. Drain, and discard water. Repeat twice. Remove short ribs from bowl, and score them diagonally across the top of the meat. Return ribs to the bowl, and rinse again. Remove, and pat dry.||In a blender or food processor, combine scallions, soy sauce, ginger, onion, garlic, sugar, mirin, orange juice and apple juice, then pulse to purée. Add a little water if you need to thin out the sauce so it combines.||Put puréed sauce in a heavy-bottomed pot or Dutch oven with a lid, add 3 cups water and stir to combine. Bring pot to a boil over high heat, then add the ribs to the pot and lower heat to a simmer. Cover pot.||Cook ribs over low for at least 2 hours. Add vegetables, cover and simmer, 30 minutes more or so, until meat is tender and vegetables are cooked through. Serve warm."},
{name: "Dijon and Cognac Beef Stew",
cat: "Soup & Stew",
time: "3 Hours",
ingredients: "1/4 pound salt pork (diced)<>1 large onion (finely diced)<>3 shallots (chopped)<>2 to 4 tablespoons unsalted butter<>2 pounds beef chuck, in 1-inch cubes<>2 tablespoons all-purpose flour<>Kosher salt<>Black pepper<>1/2 cup Cognac<>2 cups beef stock<>1/2 cup Dijon mustard<>4 tablespoons Pommery mustard or other whole-grain Dijon mustard<>4 large carrots, peeled and cut into half-moon slices<>1/2 pound mushrooms, stemmed, cleaned and quartered<>1/4 cup red wine",
steps: "Place salt pork in a Dutch oven over low heat, and cook until fat is rendered. Remove solid pieces with a slotted spoon, and discard. Raise heat, and add onion and shallots. Cook until softened but not browned, 10 to 15 minutes. Use a slotted spoon to transfer to a large bowl.||If necessary, add 2 tablespoons butter to the pot to augment fat. Dust beef cubes with flour, and season with salt and pepper. Shake off excess flour, and place half the cubes in the pot. Cook over medium-high heat until well browned, almost crusty, on all sides, then transfer to a bowl with onions. Repeat with remaining beef.||Add Cognac to the empty pot, and cook, stirring, until the bottom is deglazed and the crust comes loose. Add stock, Dijon mustard and 1 tablespoon Pommery mustard. Whisk to blend, then return meat and onion mixture to pot. Lower heat, partly cover, and simmer gently until meat is very tender, about 1 1/2 hours.||Add carrots, and continue simmering for 30 minutes, or until slices are tender. As they cook, heat 2 tablespoons butter in a medium skillet over medium-high, and sauté mushrooms until browned.||Stir mushrooms into stew along with remaining mustard and red wine. Simmer 5 minutes, then taste, and adjust seasoning. Serve hot."},
{name: "Oliver's Chicken Stew",
cat: "Soup & Stew",
time: "1 Hour",
ingredients: "3½-4 pound chicken (rinsed)<>8 cups chicken stock<>Salt<>Freshly ground black pepper<>5 medium carrots (thickly sliced)<>4 medium leeks, tender white part only (thickly sliced)<>4 celery stalks (thickly sliced)<>4 cloves garlic (smashed)<>1 teaspoon thyme (chopped)<>1 bay leaf<>3 sprigs flat-leaf parsley<>1/2 cup stellini (tiny star pasta)<>3 tablespoons unsalted butter<>1 tablespoon lemon juice<>1 tablespoon chopped tarragon<>1/4 cup chopped flat-leaf parsley<>6 slices toasted Italian bread<>1/4 cup extra-virgin olive oil<>1/2 cup grated Parmesan cheese",
steps: "Place the chicken in a 6-quart pot, breast side down. Add the stock, lightly seasoned with salt and pepper, and bring to a boil, skimming often. Add the carrots, leeks, celery, garlic, thyme, bay leaf and parsley and simmer. After 15 minutes, flip the chicken and cook for 25 minutes more. Remove the chicken and let cool.||Discard the bay leaf and parsley. Strain the vegetables, reserving the vegetables and the liquid. Return the stock to the pot; bring to a simmer. Pull the chicken meat off the bones. Add the pasta to the stock and cook for 3 minutes, then whisk in the butter, lemon juice, tarragon and parsley. Add the chicken and vegetables; heat through.||To serve, place a piece of toast in the bottom of each of 6 bowls, then drizzle with olive oil and sprinkle with Parmesan. Top with stew."},
{name: "Red Wine Chicken Stew",
cat: "Soup & Stew",
time: "30 Minutes",
ingredients: "8 medium bone-in chicken thighs (3 pounds), skin removed<>2 tablespoons all-purpose flour<>3/4 teaspoon kosher salt, plus more to taste<>1/2 teaspoon freshly ground black pepper, plus more to taste<>4 tablespoons olive oil (divided)<>1 package (14-ounce) frozen peeled pearl onions, thawed and patted dry<>2 cups carrot and/or parsnip (about 10 ounces), peeled, diced<>2 cups celery root, rutabaga, and/or turnip (about 10 ounces), peeled, large-diced<>3 cloves garlic (minced)<>1 tablespoon tomato paste (plus 1 teaspoon)<>1 tablespoon fresh thyme (chopped)<>3/2 cups dry red wine (such as pinot noir or merlot)<>2 cups low-sodium chicken broth<>1 bay leaf<>2 teaspoons red wine vinegar<>Fresh flat-leaf parsley, for garnish (optional)",
steps: "In a large bowl, combine the chicken with the flour and 1/4 teaspoon each of the salt and pepper, and toss to coat evenly. In a large, heavy pot such as a Dutch oven, over medium-high heat, heat 2 tablespoons of the oil until shimmering. Add half of the chicken and cook until golden on both sides, about 3 minutes per side, then transfer to a plate. Repeat with the remaining chicken.||Add the remaining oil to the empty pot, followed by the onions and the diced vegetables and cook, stirring occasionally, softened slightly, about 4 minutes. Add the garlic and cook for 30 seconds more, then stir in the tomato paste and thyme. Add the wine, bring to a boil and cook, uncovered, for about 2 minutes. Add the broth, bay leaf and the remaining 1/2 teaspoon salt and 1/4 teaspoon pepper and return to a boil.||Return the chicken, along with any accumulated juices, to the pot. Reduce the heat to medium-low, cover, and simmer until the chicken is cooked through and the vegetables are tender, about 25 minutes. Using a slotted spoon, transfer the chicken and vegetables to a rimmed serving plate and tent with foil. Increase the heat to high and cook until the sauce is reduced to about 2 cups, 5 to 10 minutes. Discard the bay leaf, then stir in the vinegar, and season to taste with additional salt and pepper, if desired. Pour the sauce over the chicken and vegetables, garnish with the parsley and serve."},
{name: "Hungarian Mushroom Soup",
cat: "Soup & Stew",
time: "30 Minutes",
ingredients: "4 tbsp butter<>2 cups Onions (chopped)<>1 lb Mushrooms (sliced)<>2 cups Chicken or vegetable stock<>1/2 cup Dry white wine<>2 tsp Dried dill<>2 tsp fresh thyme leaves (Minced)<>2 tsp Paprika<>2 tbsp Soy sauce<>1 cup Milk<>3 tbsp Flour<>1/4 cup Sour cream<>2 tbsp Lemon juice<>2 tbsp Fresh italian parsley",
steps: "In a heavy pot or dutch oven sauté onions and mushrooms in butter over medium heat until onions are soft and translucent, about 15 minutes. Add dill, thyme, paprika, chicken broth, soy sauce and white wine. Bring to a simmer and cook until the liquid reduces by half. In a small bowl, whisk flour into milk until smooth. Add the milk mixture to the soup and cook until the soup begins to thicken, about 10 more minutes.||Over low heat, slowly stir in the sour cream, and lemon juice until both are completely combined. Garnish the soup with parsley and serve hot."},
{name: "Homemade Ramen",
cat: "Soup & Stew",
time: "30 Minutes",
ingredients: "2 large eggs<>1 tablespoon olive oil<>4 cloves garluc (minced)<>1 tablespoon ginger (grated)<>4 cups chicken broth (reduced sodium)<>4 ounces shiitake mushrooms<>1 tablespoon soy sauce (reduced sodium)<>3 packages (5.6oz) refrigerated Yaki-Soba (seasoning sauce packets discarded)<>3 cups baby spinach<>8 slices Narutomaki (optional)<>1 carrot (Grated)<>2 tablespoons chives (chopped)",
steps: "Place eggs in a large saucepan and cover with cold water by 1 inch. Bring to a boil and cook for 1 minute. Cover eggs with a tight-fitting lid and remove from heat; set aside for 8-10 minutes. Drain well and let cool before peeling and halving.||Heat olive oil in a large stockpot or Dutch oven over medium heat. Add garlic and ginger, and cook, stirring frequently, until fragrant, about 1-2 minutes.||Whisk in chicken broth, mushrooms, soy sauce and 3 cups water.||Bring to a boil; reduce heat and simmer until mushrooms have softened, about 10 minutes. Stir in Yaki-Soba until loosened and cooked through, about 2-3 minutes.||Stir in spinach, Narutomaki, carrot and chives until the spinach begins to wilt, about 2 minutes.||Serve immediately, garnished with eggs."},
{name: "Broccolini (or Asparagus) and Carrots",
cat: "Greens",
time: "na",
ingredients: "1/3 cup chicken broth<>2 teaspoons soy sauce<>1 teaspoon corn starch<>1 teaspoon vegetable oil<>1/2 pound broccoli or asparagus<>1/2 carrot (thinly sliced)",
steps: "In a small bowl, combine the broth, soy sauce, and corn starch, stirring to dissolve.||In a large, nonstick skillet over high heat, heat the oil. Sauté green vegetables until bright green (about 2 minutes). Add the broth mixture and carrots. Cook, stirring constantly until vegetables are tender and sauce is thickened (about 3 minutes)."},
{name: "Smashed Potatoes",
cat: "Greens",
time: "na",
ingredients: "2 medium potatoes<>Butter<>Half and half<>Garlic powder<>Dill|Salt<>Pepper",
steps: "Smash?"},
{name: "Mashed Potaotes",
cat: "Greens",
time: "na",
ingredients: "4-5 Idaho potatoes (peeled and diced into ½-inch cubes)<>1 tablespoon butter<>3/2 cups heavy cream<>2 pinches salt<>1 pinch black pepper",
steps: "Boil potatoes until tender (about 15 minutes).||Drain.||Combine potatoes with butter, cream, salt and pepper in large bowl. Mix or mash to an even but not too fine cosistency. Bake in large oven-proof Casserole for about 15 minutes at 350 degrees until golden brown."},
{name: "Roasted Potatoes, Carrots, Parsnips and Brussel Sprouts",
cat: "Greens",
time: "1 Hour",
ingredients: "1/3 cup extra-virgin olive oil<>3 medium carrots (about 3/4 pound), cut into 1½-inch thick circles<>3/2 cups Brussels sprouts (about 1/2 pound), halved<>4 cups red bliss potatoes (about 1 pound), cut into 1½-inch thick slices<>3 medium parsnips (about 1 pound), cut into 1½-inch thick slices<>1 cup sweet potatoes (about 1 pound), cut into 1½-inch thick slices<>1 tablespoon dried oregano<>1 tablespoon dried rosemary<>1 teaspoon dried thyme<>1 teaspoon dried basil<>1/4 teaspoon sea salt<>1 teaspoon freshly ground black pepper",
steps: "Preheat oven to 400 degrees.||Grease an 11 by 17-inch baking sheet pan with extra-virgin olive oil. Place vegetables in baking sheet and add the dried herbs, salt and pepper. Toss well, evenly coating all the vegetables with the seasonings and oil. Add more oil if the vegetables seem dry.||Spread the vegetables evenly on a large baking sheet. Place on middle rack in oven and bake for 35 to 40 minutes."},
{name: "Nobu's Chicken Stock",
cat: "Other",
time: "3½ Hours",
ingredients: "Back and neck from a 3-pound chicken<>1 medium carrot, cut into ½-inch pieces<>1 medium onion, cut into ½-inch pieces<>1 bulb garlic, cut in half, skin on<>1 2-inch piece of ginger, cut into ¼-inch pieces<>6 cups water",
steps: "Heat the oven to 425 degrees. Roast the back and neck in a shallow roasting pan until lightly browned, about 20 minutes. Lower the heat to 375 and add the remaining ingredients, except the water. Roast for another 35 to 40 minutes.||Transfer the mixture to a small stockpot. Place the roasting pan on top of the stove over high heat. Add 1 cup of water. Bring to a boil, scraping vigorously to get the browned bits from the bottom of the pan. Pour this over the bones and vegetables. Add the remaining water. Bring to a boil. Lower the heat and simmer for 2 hours. Strain through a fine sieve."},
{name: "Basic Stovetop Rice",
cat: "Other",
time: "45~ Minutes",
ingredients: "1 cup rice (long-grain or medium-grain, like basmati or jasmine; short-grain, like sushi rice; or brown rice)",
steps: "Pour rice into a bowl, and fill it with cold water. Swirl the grains, using your fingers. Tip out any starchy water, and repeat until water runs almost clear.||Combine rice and water in a pot: For most long-grain and medium-grain rice, pair 1 cup rice and 1 1/3 cups water. For short-grain rice, use 1 cup rice and 1 cup water. For most brown rice, combine 1 cup rice and 1 3/4 cups water. The rice and water should not come more than halfway up the sides of your pot; the mixture will double in volume as it cooks.||Bring water to a hard boil over medium-high heat. The water's entire surface should break with big, constant bubbles. As soon as water is boiling, give it a vigorous stir with a spatula or wooden spoon, making sure to scrape at any grains at the bottom of the pot. Cover it with a lid and turn the heat to low.||Cook long-grain and medium-grain rice for 15 minutes; short-grain varieties for 20 minutes; and brown rice for 30 minutes.||When allotted time has passed, or when you hear a change in sound – if you listen closely, you’ll notice the sounds will slowly change from a bubbly simmer to a steamy sort of flutter – turn off heat and let rice rest for about 10 to 15 minutes before serving.||To cook in an oven, bring rice to a boil on the stovetop, stir, cover and put it in a 350-degree oven to cook through (about 17 minutes for most white rice). Rest it covered at room temperature, for 10 minutes.||To cook in a multicooker, rinse rice and pressure cook on high (about 3 minutes for short-grain rice; 8 minutes for long-grain rice; 22 minutes for brown rice). Open cooker after it’s depressurized naturally, then loosely cover the pot with a dish towel and plate and let it rest for 10 minutes."},
{name: "Stuffing",
cat: "Other",
time: "na",
ingredients: "3/2 cup sauted onions (garlic)<>1 box ritz crackers (3 packages), crushed fine<>2 eggs (beaten)1 cup cold water<>1 half cup diced celery<>1 large carrot (grated)",
steps: "Blend onions into crushed crackers.||Add 2 beaten eggs and all other ingredients.||Either put into turkey or bake in dish for 20 minutes."}

]

function stringTogether(x){
var str = ""
for (var i=0; i<x.length; i++){
var xi = x[i]; if (xi[0] == "(" || xi[1] == "-") {xi = xi[0] + xi[1].toUpperCase() + xi.substring(2)}
str = str + " " + xi
}
return str.substring(1)
}


function rp(x){
if (typeof x == "number") {var r = recipeList[x]}
else {var r = x}
var ingredients = r["ingredients"].split("<>").map(x => x.split(" ").map(ph => ph[0].toUpperCase() + ph.substring(1))).map(x => "---" + stringTogether(x) + "---").toString().replace("---","[\"").replaceAll("---,---","\"],[\"").replace("---","\"]")
var steps = "\"" + r["steps"].replaceAll("||","\",\"") + "\""

var array = []
array.push(r["name"]); array.push(r["cat"]); array.push(r["time"]);
array.push(ingredients); array.push(steps)

return array
}



function createOldRecipe(x,p){
var div = document.createElement("div"); div.style = "background-color: black; color: white; padding: 5vw; margin-bottom: 20px; width: 95%;"
  for (var i=0; i<x.length; i++){
var el = document.createElement("input"); el.style = "padding-left: 20px; margin-bottom: 20px; width: 95%; height: auto;"; el.value = x[i]; div.appendChild(el);
el.onclick = function(event){cp(event)}
}

p.appendChild(div)
}

function cOR(start,end){
var parent = document.getElementById("mainList"); var pl = parent.childNodes.length;
for (var i=0; i<pl; i++) {parent.childNodes[0].remove()}

if (start == undefined) {var s = 0} else {var s = start}
if (end == undefined) {var e = recipeList.length} else {var e = end}
for (var i=s; i<e; i++){  createOldRecipe(rp(i),parent) }}

function cp(event) {
  var e = event.composedPath()[0]
  e.select();
  navigator.clipboard.writeText(e.value);
}
